"""
Unit tests for Chora Server/API.
"""
import pytest
from fastapi.testclient import TestClient
from unittest.mock import MagicMock, patch

# Import CreateApp
from chora.server.app import create_app

@pytest.fixture
def client():
    app = create_app()
    return TestClient(app)

def test_create_agent(client):
    """Test POST /agents/ creates an agent."""
    response = client.post("/agents/", json={"name": "TestAlice"})
    assert response.status_code == 200
    # ID is a UUID string, might not start with agent- if generated by uuid4 directly
    assert len(response.json()) > 10

def test_create_extent(client):
    """Test POST /extents/ creates an extent."""
    payload = {
        "name": "TestPark",
        "min_x": 0.0, "min_y": 0.0,
        "max_x": 1.0, "max_y": 1.0
    }
    response = client.post("/extents/", json=payload)
    assert response.status_code == 200
    assert len(response.json()) > 10

@patch("chora.server.hub.manager.broadcast")
def test_log_encounter_logs_and_broadcasts(mock_broadcast, client):
    """Test encounters loop: log -> broadcast."""
    # 1. Create agent/extent first
    a_id = client.post("/agents/", json={"name": "Alice"}).json()
    e_id = client.post("/extents/", json={
        "name": "Park", "min_x":0,"min_y":0,"max_x":1,"max_y":1
    }).json()
    
    # 2. Log encounter
    enc_payload = {
        "agent_id": a_id,
        "extent_id": e_id,
        "duration_minutes": 30
    }
    response = client.post("/encounters/", json=enc_payload)
    
    assert response.status_code == 200
    
    # 3. Check broadcast called
    mock_broadcast.assert_called_once()
    assert "New Encounter" in mock_broadcast.call_args[0][0]

def test_vector_embedding_endpoint(client):
    """Test /vectors/embed logic."""
    # Patch where it is DEFINED, or where it is IMPORTED.
    # Since api.py does `from chora.embeddings import get_embedding_model` inside function,
    # we patch `chora.embeddings.get_embedding_model` or `chora.embeddings.local.get_embedding_model`?
    # `chora.embeddings` imports from `local`.
    with patch("chora.embeddings.get_embedding_model") as mock_get:
        instance = MagicMock()
        instance.embed_text.return_value = [0.99] * 3
        mock_get.return_value = instance
        
        response = client.post("/vectors/embed", params={"text": "hello"})
        assert response.status_code == 200
        assert response.json() == [0.99] * 3
